name: projeto_p2  # Nome do projeto Flutter
description: "A new Flutter project."

# O seguinte impede que o pacote seja publicado acidentalmente no pub.dev.
publish_to: 'none'  # Remova esta linha se quiser publicar no pub.dev.

version: 1.0.0+1  # Versão e número de build do aplicativo.

environment:
  sdk: ^3.5.3  # Definição da versão do SDK do Flutter.

dependencies:
  flutter:
    sdk: flutter  # Dependência básica do Flutter.

  firebase_core: "^2.0.0"  # Firebase Core para integração com Firebase.
  firebase_auth: "^4.0.0"  # Firebase Auth para autenticação.

  cupertino_icons: ^1.0.8  # Ícones do Cupertino para ícones estilo iOS.

dev_dependencies:
  flutter_test:
    sdk: flutter  # Dependência para testes.

  flutter_lints: ^4.0.0  # Linting recomendado para boas práticas de codificação.

flutter:
  uses-material-design: true  # Garante que os ícones Material sejam usados.

  # Se for necessário adicionar assets ao seu aplicativo, você pode usar a seção abaixo.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Para fontes personalizadas, você pode adicionar algo assim:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
